"use client";

import { useCallback, useSyncExternalStore } from "react";

/**
 * The cabinet's noises, synthesised rather than sampled.
 *
 * Every cue here is generated by the Web Audio API at the moment it plays.
 * Nothing is downloaded, nothing is bundled, and there is no audio file
 * anywhere in the repo, which matters for three separate reasons:
 *
 *   LICENCE. Shipping music means shipping somebody's copyright, with terms to
 *   honour and attribution to keep correct. This site's whole premise is that
 *   everything on it can be traced, and a track we cannot license cleanly has
 *   no business being the one thing on the page nobody can check.
 *
 *   POLICY. The content security policy is `media-src 'self'` with no external
 *   origins. A hosted track would be blocked outright, and loosening the policy
 *   to admit a CDN is a real cost for a decorative feature.
 *
 *   WEIGHT. These cues are a few hundred bytes of code. A music bed is
 *   megabytes, on a site whose largest asset today is a 180KB word-vector file.
 *
 * The palette is deliberately dry and percussive, short, hard-edged, no
 * reverb tails, because the visual design is flat spot inks with no gradients
 * and a lush pad would sound like a different product.
 *
 * If a licensed music bed is wanted later, `playCue` is the seam: give it a
 * branch that plays an `<audio>` element instead, keep the mute store as is,
 * and add the origin to `media-src`.
 */

export type Cue =
  /** A card, word or option was picked. The smallest possible acknowledgement. */
  | "tap"
  /** Called it right. */
  | "right"
  /** Called it wrong. */
  | "wrong"
  /** Evidence arriving, bars growing, a reveal opening. */
  | "reveal"
  /** A round begins. */
  | "start"
  /** A round ends without a new best. */
  | "over"
  /** A personal best was beaten. */
  | "best";

/* ------------------------------------------------------------------ mute -- */

const KEY = "llai-muted";
const EVENT = "llai-muted-change";

let cache = false;
let cacheRaw: string | null = null;

function readMuted(): boolean {
  let raw: string | null = null;
  try {
    raw = localStorage.getItem(KEY);
  } catch {
    return cache;
  }
  if (raw === cacheRaw) return cache;
  cacheRaw = raw;
  cache = raw === "1";
  return cache;
}

function subscribe(onChange: () => void) {
  window.addEventListener(EVENT, onChange);
  window.addEventListener("storage", onChange);
  return () => {
    window.removeEventListener(EVENT, onChange);
    window.removeEventListener("storage", onChange);
  };
}

/**
 * Sound on/off, remembered.
 *
 * Read through `useSyncExternalStore` rather than an effect, because the
 * compiler rules here forbid reading browser state during render and forbid
 * calling setState from an effect body. The server snapshot is `false` so the
 * markup matches on hydration.
 */
export function useMuted(): [boolean, () => void] {
  const muted = useSyncExternalStore(subscribe, readMuted, () => false);

  const toggle = useCallback(() => {
    const next = !readMuted();
    try {
      localStorage.setItem(KEY, next ? "1" : "0");
    } catch {
      // Private browsing, the preference just will not survive a reload.
    }
    window.dispatchEvent(new Event(EVENT));
    if (!next) playCue("tap");
  }, []);

  return [muted, toggle];
}

/* ----------------------------------------------------------------- audio -- */

type Ctx = AudioContext & { __llaiMaster?: GainNode };

let context: Ctx | null = null;

/**
 * The shared context, made on first use.
 *
 * Browsers refuse to start audio outside a user gesture, so this is only ever
 * called from a click or a state change that a click caused. A context that
 * arrives suspended is resumed; if the browser still refuses, every cue below
 * quietly does nothing rather than throwing into a render.
 */
function ensureContext(): Ctx | null {
  if (typeof window === "undefined") return null;
  if (context) {
    if (context.state === "suspended") void context.resume();
    return context;
  }

  const Ctor =
    window.AudioContext ??
    (window as unknown as { webkitAudioContext?: typeof AudioContext })
      .webkitAudioContext;
  if (!Ctor) return null;

  try {
    context = new Ctor() as Ctx;
  } catch {
    return null;
  }

  const master = context.createGain();
  // Well under unity. Game feedback should sit under a podcast, not over it.
  master.gain.value = 0.22;
  master.connect(context.destination);
  context.__llaiMaster = master;

  return context;
}

type Note = {
  /** Hertz. */
  hz: number;
  /** Seconds from the start of the cue. */
  at: number;
  /** Seconds. */
  length: number;
  type?: OscillatorType;
  /** Peak gain, before the master. */
  level?: number;
  /** Slide to this frequency across the note. */
  to?: number;
};

function play(notes: Note[]) {
  const ctx = ensureContext();
  const master = ctx?.__llaiMaster;
  if (!ctx || !master) return;

  const now = ctx.currentTime;

  for (const note of notes) {
    const osc = ctx.createOscillator();
    const gain = ctx.createGain();

    osc.type = note.type ?? "triangle";
    osc.frequency.setValueAtTime(note.hz, now + note.at);
    if (note.to !== undefined) {
      osc.frequency.exponentialRampToValueAtTime(
        Math.max(1, note.to),
        now + note.at + note.length,
      );
    }

    // A short attack and an exponential fall, dry, no tail.
    const peak = note.level ?? 1;
    gain.gain.setValueAtTime(0.0001, now + note.at);
    gain.gain.exponentialRampToValueAtTime(peak, now + note.at + 0.008);
    gain.gain.exponentialRampToValueAtTime(
      0.0001,
      now + note.at + note.length,
    );

    osc.connect(gain);
    gain.connect(master);
    osc.start(now + note.at);
    osc.stop(now + note.at + note.length + 0.02);
  }
}

/** Filtered noise, for the one cue that wants a texture rather than a pitch. */
function playNoise(length: number, hz: number, level: number) {
  const ctx = ensureContext();
  const master = ctx?.__llaiMaster;
  if (!ctx || !master) return;

  const frames = Math.floor(ctx.sampleRate * length);
  const buffer = ctx.createBuffer(1, frames, ctx.sampleRate);
  const data = buffer.getChannelData(0);
  for (let i = 0; i < frames; i++) {
    // Fades across the buffer, so the source needs no envelope of its own.
    data[i] = (Math.random() * 2 - 1) * (1 - i / frames);
  }

  const source = ctx.createBufferSource();
  source.buffer = buffer;

  const filter = ctx.createBiquadFilter();
  filter.type = "bandpass";
  filter.frequency.value = hz;
  filter.Q.value = 0.8;

  const gain = ctx.createGain();
  gain.gain.value = level;

  source.connect(filter);
  filter.connect(gain);
  gain.connect(master);
  source.start();
}

const CUES: Record<Cue, () => void> = {
  tap: () => play([{ hz: 880, at: 0, length: 0.05, level: 0.35, type: "square" }]),

  // Two notes up. Short enough to fire on every correct answer without nagging.
  right: () =>
    play([
      { hz: 587.33, at: 0, length: 0.09, level: 0.6 },
      { hz: 880, at: 0.07, length: 0.14, level: 0.55 },
    ]),

  // Down a minor third, with a dull knock under it. Disappointment, not alarm.
  wrong: () => {
    play([
      { hz: 233.08, at: 0, length: 0.16, level: 0.5, type: "sawtooth" },
      { hz: 185, at: 0.09, length: 0.2, level: 0.4, type: "sawtooth" },
    ]);
    playNoise(0.12, 220, 0.18);
  },

  // A quiet upward sweep as the evidence lands.
  reveal: () =>
    play([{ hz: 320, to: 720, at: 0, length: 0.28, level: 0.28, type: "sine" }]),

  start: () =>
    play([
      { hz: 392, at: 0, length: 0.1, level: 0.45 },
      { hz: 523.25, at: 0.06, length: 0.12, level: 0.45 },
    ]),

  over: () =>
    play([
      { hz: 392, at: 0, length: 0.12, level: 0.4 },
      { hz: 329.63, at: 0.1, length: 0.18, level: 0.4 },
    ]),

  // The only cue allowed to be pleased with itself.
  best: () =>
    play([
      { hz: 523.25, at: 0, length: 0.1, level: 0.5 },
      { hz: 659.25, at: 0.08, length: 0.1, level: 0.5 },
      { hz: 783.99, at: 0.16, length: 0.1, level: 0.5 },
      { hz: 1046.5, at: 0.24, length: 0.24, level: 0.45 },
    ]),
};

/**
 * Play a cue, unless the reader has muted or the browser will not have it.
 *
 * Safe to call from anywhere, including an effect. It never throws and never
 * returns anything a caller has to handle.
 */
export function playCue(cue: Cue) {
  if (typeof window === "undefined") return;
  if (readMuted()) return;
  try {
    CUES[cue]?.();
  } catch {
    // Audio is decoration. It is never worth breaking a round over.
  }
}
