import raw from "@data/nextword.json";

/**
 * The bigram opponent for module 1.
 *
 * Generated by data/scripts/build-nextword.mjs from a public-domain book. The
 * probabilities are real counts, not illustrations — including the ones where
 * the model is confidently wrong, which are the useful rounds.
 */

export type NextWordRound = {
  lead: string;
  cue: string;
  truth: string;
  options: string[];
  modelGuess: string;
  modelConfidence: number;
  modelTop: { word: string; probability: number }[];
};

export const NEXT_WORD = raw as {
  generatedBy: string;
  source: { title: string; author: string; via: string; licence: string };
  model: { kind: string; vocabulary: number; trainedOnWords: number };
  rounds: NextWordRound[];
};
